name: growth_standards
description: A Dart implementation of various growth standards, WHO, CDC, Fenton, Intergrowth, etc.
version: 4.3.0
repository: https://github.com/devsdocs/growth_standards

environment:
  sdk: ^3.8.0

dependencies:
  clock: ^1.1.2
  dart_numerics: ^0.0.6
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  super_measurement: 4.0.0

dev_dependencies:
  build_runner: ^2.10.5
  freezed: ^3.2.4
  json_serializable: ^6.11.4
  lint: ^2.2.0
  test: ^1.24.0
